replicaCount: 1

image:
  repository: bharathaws/myapp
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  host: myapp.local
  tls: false
  tlsSecret: ""
