containers:
  - name: my-app
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    ports:
      - containerPort: 5000
    readinessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 15
      periodSeconds: 20
