spec:
  rules:
    - host: myapp.dev.example.com   # update with your DNS or nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app
                port:
                  number: 80
